# Generated by Django 2.2.24 on 2021-09-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0004_socialapp_cert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialapp",
            name="cert",
        ),
    ]
